deploy_path: /var/projects/tutorials
host: stackbuilders@localhost
port: 10022
repo: git@github.com:stackbuilders/tutorials.git
revision: origin/tutorials
build_script:
  - stack setup
  - source config/local.env && make rebuild
