deploy_path: /var/projects/tutorials
host: stackbuilders@staging.stackbuilders.com
repo: git@stackbuilders-tutorials:stackbuilders/tutorials.git
revision: origin/tutorials
build_script:
  - stack setup
  - source config/staging.env && make rebuild
